# -*- coding: utf-8 -*-
"""Detect face images with age gender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18mATwoNSiAYbsaWM8e5mnjZZfHyckBrK
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow
from keras.layers import *
from keras.models import Sequential,Model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.applications.resnet50 import ResNet50
from keras.applications.mobilenet_v2 import MobileNetV2
from keras.applications.efficientnet import EfficientNetB0

# 1. Install the Kaggle API
!pip install -q kaggle

# 2. Set your new API token
import os
os.environ['KAGGLE_API_TOKEN'] = " "

!kaggle datasets download -d jangedoo/utkface-new

!unzip -q utkface-new.zip -d UTKFace_dataset

print("Files found:", len(os.listdir("UTKFace_dataset")))

path="/content/UTKFace_dataset/utkface_aligned_cropped/UTKFace"

age=[]
Gendar=[]
file_path=[]
for file in os.listdir(path):
  age.append(int(file.split('_')[0]))
  Gendar.append(int(file.split('_')[1]))
  file_path.append(file)

len(Gendar)

df=pd.DataFrame({'age':age,'Gendar':Gendar,'file_path':file_path})

df.head()

train_data=df.sample(frac=1,random_state=0).iloc[:20000]
test_data=df.sample(frac=1,random_state=0).iloc[20000:]

test_data.shape

train_datagen=ImageDataGenerator(rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen=ImageDataGenerator(
    rescale=1./255
)

train_generator=train_datagen.flow_from_dataframe(train_data,
                                                  directory=path,
                                                  x_col='file_path',
                                                  y_col=['age','Gendar'],
                                                  target_size=(200,200),
                                                  class_mode='multi_output',
                                                  batch_size=32)
test_generator=test_datagen.flow_from_dataframe(test_data,
                                                directory=path,
                                                x_col='file_path',
                                                y_col=['age','Gendar'],
                                                target_size=(200,200),
                                                class_mode='multi_output',
                                                batch_size=32)

import tensorflow as tf

def wrap_generator(gen):
    for x, y in gen:
        yield x, (y[0], y[1])

output_signature = (
    tf.TensorSpec(shape=(None, 200, 200, 3), dtype=tf.float32),
    (
        tf.TensorSpec(shape=(None,), dtype=tf.float32),
        tf.TensorSpec(shape=(None,), dtype=tf.float32),
    )
)

train_ds = tf.data.Dataset.from_generator(
    lambda: wrap_generator(train_generator),
    output_signature=output_signature
)

test_ds = tf.data.Dataset.from_generator(
    lambda: wrap_generator(test_generator),
    output_signature=output_signature
)

model=ResNet50(include_top=False,input_shape=(200,200,3))

model.trainable=False
output=model.layers[-1].output

flatten=Flatten()(output)

dense1=Dense(512,activation='relu')(flatten)
dense2=Dense(512,activation='relu')(dense1)

dense3=Dense(512,activation='relu')(dense1)
dense4=Dense(512,activation='relu')(dense2)

output1=Dense(1,activation='linear',name='age')(dense3)
output2=Dense(1,activation='sigmoid',name='Gendar')(dense4)

model=Model(inputs=model.input,outputs=[output1,output2])

model.compile(optimizer='adam',loss={'age':'mae','Gendar':'binary_crossentropy'},metrics={'age': 'mae', 'Gendar': 'accuracy'},loss_weights={'age':1,'Gendar':99})

# steps_per_epoch = len(train_data) // 32
# validation_steps = len(test_data) // 32

# model.fit(
#     train_ds,
#     epochs=10,
#     validation_data=test_ds,
#     steps_per_epoch=steps_per_epoch,
#     validation_steps=validation_steps
# )



"""***now using the MobileNetV2***"""

model=MobileNetV2(include_top=False,input_shape=(200,200,3))

model.trainable=False
output=model.layers[-1].output

flatten = GlobalAveragePooling2D()(output)

dense1=Dense(512,activation='relu')(flatten)
dense2=Dense(512,activation='relu')(dense1)

dense3=Dense(512,activation='relu')(dense1)
dense4=Dense(512,activation='relu')(dense2)

output1=Dense(1,activation='linear',name='age')(dense3)
output2=Dense(1,activation='sigmoid',name='Gendar')(dense4)

model=Model(inputs=model.input,outputs=[output1,output2])

model.compile(optimizer='adam',loss={'age':'mae','Gendar':'binary_crossentropy'},metrics={'age': [tf.keras.metrics.R2Score(name='r2')], 'Gendar': 'accuracy'},loss_weights={'age':1,'Gendar':99})



steps_per_epoch = len(train_data) // 32
validation_steps = len(test_data) // 32

model.fit(
    train_ds,
    epochs=10,
    validation_data=test_ds,
    steps_per_epoch=steps_per_epoch,
    validation_steps=validation_steps
)

# ==================== WEBCAM CAPTURE ====================
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import cv2
import numpy as np
import matplotlib.pyplot as plt

def take_photo(filename='photo.jpg', quality=0.8):
    js = Javascript('''
        async function takePhoto(quality) {
            const div = document.createElement('div');
            const capture = document.createElement('button');
            capture.textContent = 'Capture';
            div.appendChild(capture);
            const video = document.createElement('video');
            video.style.display = 'block';
            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            document.body.appendChild(div);
            div.appendChild(video);
            video.srcObject = stream;
            await video.play();
            google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);
            await new Promise((resolve) => capture.onclick = resolve);
            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);
            stream.getVideoTracks()[0].stop();
            div.remove();
            return canvas.toDataURL('image/jpeg', quality);
        }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])
    with open(filename, 'wb') as f:
        f.write(binary)
    return filename

photo_path = take_photo()

# ==================== DETECT FACE ====================
img = cv2.imread(photo_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(60, 60))

if len(faces) == 0:
    print("No face detected — retake with better lighting/angle.")
else:
    (x, y, w, h) = faces[0]
    face_crop = img[y:y+h, x:x+w]
    face_resized = cv2.resize(face_crop, (200, 200))
    face_rgb = cv2.cvtColor(face_resized, cv2.COLOR_BGR2RGB)

    plt.imshow(face_rgb)
    plt.axis('off')
    plt.title("Detected face")
    plt.show()

    # ==================== PREDICT ====================
    face_input = face_rgb.astype('float32') / 255.0
    face_input = np.expand_dims(face_input, axis=0)

    age_pred, gender_pred = model.predict(face_input)

    predicted_age = int(round(age_pred[0][0]))
    predicted_gender = "Male" if gender_pred[0][0] < 0.5 else "Female"

    print(f"Predicted age: {predicted_age}")
    print(f"Predicted gender: {predicted_gender}")

